Tests for unresolved symbols when linking to libm

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -164,6 +164,7 @@ if [ "$RTDIR" = "" ] ; then
 	    RTAI=$(echo $rtai | grep buildvars | sed s^/.buildvars^^g)
 	    if [ "$RTAI" != "" ] ; then
 	        RTDIR=$RTAI
+                RTAI_VER=1
 	    fi
 	done
     fi
@@ -177,15 +178,13 @@ fi
 #
 # check RTDIR for a valid RTOS signature
 #
-if [ ! -f $RTDIR/rtl.mk ] ; then
-    if [ ! -f $RTDIR/bin/rtai-config ] ; then
-        if [ ! -f $RTDIR/.buildvars ] ; then
+if [ ! -f $RTDIR/rtl.mk ] && \
+    [ ! -f $RTDIR/bin/rtai-config ] && \
+    [ ! -f $RTDIR/.buildvars ] ; then
 	# no rtai or rtlinux signatures found, then exit..
-    	    echo "No RTAI or RTLinux signatures found in $RTDIR"
-    	    usage
-	    exit -1
-	fi
-    fi
+    echo "No RTAI or RTLinux signatures found in $RTDIR"
+    usage
+    exit -1
 fi
 
 # try to find out where man files are stored on this system.
@@ -221,6 +220,53 @@ source "$TKCONFIG"
 fi
 
 
+# Test the compatability of libm for realtimr or kernel modules.
+if [ -r $RTDIR/modules/rtai_libm.o ] ; then
+    # RTAI_VER is set, so don't need to define MATHLIB
+    MATHLIB=
+    USE_RTLIBM=1
+    echo "Using RTAI's libm kernel module"
+else
+    echo "Testing for a suitable libm... Some symbols may be printed if a test fails."
+    # With RTAI we will assume that rtai_libm (or rtai_math) will
+    # work. For RTLinux, a couple of tests need to be done.
+    rm -f src/tests/mathtest.o src/tests/mathtest 2>/dev/null
+    # compile a sample first.
+    gcc -O0 -c src/tests/mathtest.c -o src/tests/mathtest.o
+
+    DIET_DIR=$(find /usr/lib -maxdepth 2 -name diet* | head -n1)
+    if [ "$DIET_DIR" != "" ] ; then
+        # Run a test to see if it will work...
+        ld -r -static src/tests/mathtest.o -o src/tests/mathtest -L$DIET_DIR/lib-i386 -lm
+        if ! nm -u src/tests/mathtest | grep -v ende ; then
+            echo "diet lib OK to use."
+            USE_DIET=1
+            MATHLIB="-L$DIET_DIR/lib-i386 -lm"
+            MATHINC="-I$DIET_DIR/include"
+        fi
+    fi
+    if [ "$USE_DIET" = "" ] ; then
+        # Test the standard libm
+    rm -f src/tests/mathtest 2>/dev/null
+    ld -r -static src/tests/mathtest.o -o src/tests/mathtest -L/usr/lib -lm
+        if ! nm -u src/tests/mathtest ; then
+            echo "libm OK to use."
+            USE_LIBM=1
+            MATHLIB="-L/usr/lib -lm"
+        else
+            # We need to link to mathstubs if we are to use the glibc libm
+            echo "libm tests failed - Using glibc libm with mathstubs."
+	    echo "If unresolved symbols are reported when loading kernel modules"
+	    echo "please file a bug report."
+            USE_LIBM=1
+	    USE_STUBS=1
+            MATHLIB="-L/usr/lib -lm \$(RTTMP_DIR)/mathstubs.o"
+        fi
+    fi
+    rm -f src/tests/mathtest.o src/tests/mathtest 2>/dev/null
+fi
+
+
 # Go on to write out the Makefile.inc
 DATE=$(date)
 
@@ -249,16 +295,14 @@ if [ -f $RTDIR/.buildvars ] ; then
     echo found an RTAI installation in $RTDIR
     echo "RTNAME = rtai" >> Makefile.inc
     echo "RTPREFIX = rtai" >> Makefile.inc
-    echo "RTAI = 1" >> Makefile.inc
+    echo "RTAI = $RTAI_VER" >> Makefile.inc
 # Added a "sed s/' = '/'='/" here (and elsewhere) because the awk split
 # fails when it finds "FOO = bar" - So we need to make sure it finds
 # "FOO=bar" instead.
     KERNEL=$(cat $RTFILE | grep LINUXDIR | sed s/' = '/'='/ | awk '{split($1, A, "=")}{print A[2]}') 2> /dev/null #'
     KERNELDIR=$(cd $KERNEL ; pwd -P )
-    MATHLIB=""
 
 elif [ -f $RTDIR/bin/rtai-config ] ; then
-#	RTFILE=$RTDIR/.buildvars
     echo found an RTAI installation in $RTDIR
     echo "RTNAME = rtai-3.0" >> Makefile.inc
     echo "RTPREFIX = rtai" >> Makefile.inc
@@ -277,7 +321,6 @@ elif [ -f $RTDIR/rtl.mk ] ; then
 # There is probably a better way of doing this without using sed !
     KERNEL=$(cat $RTFILE | grep RTLINUX_DIR | sed s/' = '/'='/ | awk '{split($1, A, "=")}{print A[2]}') 2> /dev/null #'
     KERNELDIR=$(cd $KERNEL ; pwd -P )
-    MATHLIB="-L/usr/lib -lm"
 fi
 
 echo "KERNELDIR = $KERNELDIR" >> Makefile.inc
@@ -286,12 +329,27 @@ if [ "$RTFILE" != "" ] ; then
     cat $RTFILE | grep CFLAGS | sed s/CFLAGS/RTFLAGS/ >> Makefile.inc
 fi
 
-echo "RTFLAGS := -I\$(INC_DIR) -I$RTDIR/include -I. \$(RTFLAGS) -DRTAPI" >> Makefile.inc
-echo "MATHLIB = $MATHLIB" >> Makefile.inc
+echo "RTFLAGS := $MATHINC -I\$(INC_DIR) -I$RTDIR/include -I. \$(RTFLAGS) -DRTAPI" >> Makefile.inc
 
 if [ "$RTFILE" != "" ] ; then
     CC=$(cat $RTFILE | grep CC | sed s/' = '/'='/ | awk '{split($1, A, "=")}{print A[2]}') 2> /dev/null #'
 fi
+
+# Set the MATHLIB link options.
+if [ "$USE_DIET" != "" ] ; then
+    echo "USE_DIET = $USE_DIET" >> Makefile.inc
+elif [ "$USE_RTLIBM" != "" ] ; then
+    echo "USE_RTLIBM = $USE_RTLIBM" >> Makefile.inc
+elif [ "$USE_LIBM" != "" ] ; then
+    if [ "$USE_STUBS" != "" ] ; then
+      echo "libm tests failed - Using glibc libm with mathstubs." >> Makefile.inc
+      echo "If unresolved symbols are reported when loading kernel modules" >> Makefile.inc
+      echo "please file a bug report." >> Makefile.inc
+    fi
+    echo "USE_LIBM = $USE_LIBM" >> Makefile.inc
+fi
+echo "MATHLIB = $MATHLIB" >> Makefile.inc
+
 if [ "$CC" = "" ] ; then
     CC=cc
 fi
@@ -376,5 +434,8 @@ for i in bin include lib rtlib ; do
 done
 
 # terminate normally
+echo
+echo " Configure finished - Please check Makefile.inc for errors."
+echo
 exit 0
 
