added rtlibm, libm, math support

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -310,7 +310,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS RTNAME RTAI RTLINUX RTLINUXPRO RTPREFIX KERNELDIR RTFLAGS RTDIR EMC2_HOME CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX SET_MAKE RANLIB ac_ct_RANLIB AR GTK_VER GTK_LIBS GTK_CFLAGS MANDIR CPP EGREP DATE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS RTNAME RTAI RTLINUX RTLINUXPRO RTPREFIX KERNELDIR RTFLAGS RTDIR EMC2_HOME CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX SET_MAKE RANLIB ac_ct_RANLIB AR GTK_VER GTK_LIBS GTK_CFLAGS MANDIR USE_LIBM USE_STUBS USE_RTLIBM MATHINC MATHLIB CPP EGREP DATE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1383,6 +1383,10 @@ if (test -z "$RTDIR" ); then
     { { echo "$as_me:$LINENO: error: RT not found, try to specify one by --with-rtai=<path>, --with-rtlinux=<path>, --with-rtlinuxpro=<path>" >&5
 echo "$as_me: error: RT not found, try to specify one by --with-rtai=<path>, --with-rtlinux=<path>, --with-rtlinuxpro=<path>" >&2;}
    { (exit 1); exit 1; }; }
+  elif (test `echo "$RTS" | wc -l` != 1 ) ; then
+    { { echo "$as_me:$LINENO: error: Multiple RT signatures found, try to specify one by --with-rtai=<path>, --with-rtlinux=<path>, --with-rtlinuxpro=<path>" >&5
+echo "$as_me: error: Multiple RT signatures found, try to specify one by --with-rtai=<path>, --with-rtlinux=<path>, --with-rtlinuxpro=<path>" >&2;}
+   { (exit 1); exit 1; }; }
   elif (test `echo $RTS | awk -F / ' {print $NF}'` = "rtai-config") ; then
     #we have found rtai-config
     #probably version 3
@@ -1421,7 +1425,8 @@ else
     RTAI=3
     RTDIR=`$RTS --prefix`
     RTDIR=$(cd $RTDIR ; pwd -P )
-    RTFLAGS=`$RTS --module-cflags` -DRTAI=3
+    RTFLAGS=`$RTS --module-cflags`
+    RTFLAGS="$RTFLAGS -DRTAI=3"
     KERNELDIR=`$RTS --linux-dir`
   elif (! test "x$RTLINUXDIR" = "x") ; then
     #FIXME add rtl-config
@@ -3123,6 +3128,66 @@ fi
 # GNU glibc math library will have to be used. This will cause problems
 # if certain functions found in libc.so are not stubbed, hence the following
 # tests and linking to mathstubs.o at a later stage.
+echo "$as_me:$LINENO: checking for kernel math support" >&5
+echo $ECHO_N "checking for kernel math support... $ECHO_C" >&6
+
+if (test -r $RTDIR/modules/rtai_libm.o ) || (test -r $($RTS --module-dir)/rtai_math.o ) ; then
+    # Found a suitable kernel module..
+    MATHLIB=
+    USE_RTLIBM=1
+    echo "$as_me:$LINENO: result: ok, using RTAI's libm kernel module" >&5
+echo "${ECHO_T}ok, using RTAI's libm kernel module" >&6
+# Note: need to search /lib/modules/`uname -r` for the math modules..
+else
+    echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+    echo "$as_me:$LINENO: checking for a suitable libm" >&5
+echo $ECHO_N "checking for a suitable libm... $ECHO_C" >&6
+    rm -f src/tests/mathtest.o src/tests/mathtest 2>/dev/null
+    # compile a sample first.
+    $CC -O -c src/tests/mathtest.c -o src/tests/mathtest.o 2>/dev/null
+
+    DIET_DIR=$(find /usr/lib -maxdepth 2 -name diet* | head -n1)
+    if (test "$DIET_DIR" != "" ) ; then
+        # Run a test to see if it will work...
+        ld -r -static src/tests/mathtest.o -o src/tests/mathtest -L$DIET_DIR/lib-i386 -lm 2>/dev/null
+        if (test "$(nm -u src/tests/mathtest | grep -v ende)" = "" ) ; then
+            echo "$as_me:$LINENO: result: diet lib OK to use." >&5
+echo "${ECHO_T}diet lib OK to use." >&6
+            USE_DIET=1
+            MATHLIB="-L$DIET_DIR/lib-i386 -lm"
+            MATHINC="-I$DIET_DIR/include"
+        fi
+    fi
+    if (test "$USE_DIET" = "" ) ; then
+        # Test the standard libm
+    rm -f src/tests/mathtest 2>/dev/null
+    ld -r -static src/tests/mathtest.o -o src/tests/mathtest -L/usr/lib -lm 2>/dev/null
+        if ! nm -u src/tests/mathtest ; then
+            echo "$as_me:$LINENO: result: libm OK to use." >&5
+echo "${ECHO_T}libm OK to use." >&6
+            USE_LIBM=1
+            MATHLIB="-L/usr/lib -lm"
+        else
+            # We need to link to mathstubs if we are to use the glibc libm
+            { echo "$as_me:$LINENO: WARNING: Using glibc libm with mathstubs.
+			If unresolved symbols are reported when loading kernel modules
+			please file a bug report." >&5
+echo "$as_me: WARNING: Using glibc libm with mathstubs.
+			If unresolved symbols are reported when loading kernel modules
+			please file a bug report." >&2;}
+            USE_LIBM=1
+	    USE_STUBS=1
+            MATHLIB="\$(RTTMP_DIR)/mathstubs.o -L/usr/lib -lm"
+        fi
+    fi
+    rm -f src/tests/mathtest.o src/tests/mathtest 2>/dev/null
+fi
+
+
+
+
+
 
 
 # Checks for libraries.
@@ -4697,6 +4762,11 @@ s,@GTK_VER@,$GTK_VER,;t t
 s,@GTK_LIBS@,$GTK_LIBS,;t t
 s,@GTK_CFLAGS@,$GTK_CFLAGS,;t t
 s,@MANDIR@,$MANDIR,;t t
+s,@USE_LIBM@,$USE_LIBM,;t t
+s,@USE_STUBS@,$USE_STUBS,;t t
+s,@USE_RTLIBM@,$USE_RTLIBM,;t t
+s,@MATHINC@,$MATHINC,;t t
+s,@MATHLIB@,$MATHLIB,;t t
 s,@CPP@,$CPP,;t t
 s,@EGREP@,$EGREP,;t t
 s,@DATE@,$DATE,;t t
