build-depend on w3c-linkchecker
This commit causes the HTML links to be validated every time the HTML
docs are built, using the W3C "checklink" program from the
w3c-linkchecker package.

This validation was optional before, because Lucid doesn't have the
w3c-linkchecker package, so we couldn't build-depend on it.  Now that we
don't support Lucid any more, we can finally add this build dependency.

Signed-off-by: Sebastian Kuzminsky <seb@highlab.com>

diff --git a/docs/src/checkref b/docs/src/checkref
--- a/docs/src/checkref
+++ b/docs/src/checkref
@@ -12,10 +12,9 @@ shift
 
 FILES="$@"
 
-# it'd be nice to build-depend on checklinks, but it's not available in Lucid
 if [ -z $(which checklink) ]; then
-    echo "*** checklink not found, install w3c-linkchecker for better coverage" 1>&2
-    exit 0
+    echo "ERROR: checklink not found, install w3c-linkchecker for HTML link validation" 1>&2
+    exit 1
 fi
 
 
