Adjusted autopkgtest scripts to run from debian/tests/
The scripts failed to find files it needed.  Also add more error
detection and reporting code to the scripts.

diff --git a/debian/tests/linuxcnc-test b/debian/tests/linuxcnc-test
--- a/debian/tests/linuxcnc-test
+++ b/debian/tests/linuxcnc-test
@@ -1,5 +1,13 @@
-#!/bin/bash -e
+#!/bin/sh
 #
 # Based on tests/single-step/
 
-linuxcnc -r linuxcnc-test.ini
+set -e
+
+cd $(dirname $0)
+
+if ! linuxcnc -r linuxcnc-test.ini ; then
+    echo "error: failed to execute linuxcnc"
+    exit 1
+fi
+exit 0
diff --git a/debian/tests/rs274-test b/debian/tests/rs274-test
--- a/debian/tests/rs274-test
+++ b/debian/tests/rs274-test
@@ -2,7 +2,12 @@
 
 set -e
 
-rs274 -g rs274.ngc > $AUTOPKGTEST_TMP/rs274.out 2>&1
+cd $(dirname $0)
+
+if rs274 -g rs274.ngc > $AUTOPKGTEST_TMP/rs274.out 2>&1 ; then
+    echo "error: failed to run rs274"
+    exit 1
+fi
 
 if ! diff -u $AUTOPKGTEST_TMP/rs274.out rs274.res ; then
     echo "error: rs274 output do not match rs274.res"
