fixes, eliminating redundant build-dep 'gettext'

diff --git a/debian/configure b/debian/configure
--- a/debian/configure
+++ b/debian/configure
@@ -22,7 +22,7 @@ Usage:
 
   Extra options:
 
-    no-docs|nodocs|nodoc
+    no-docs|nodocs|nodoc|no-doc
         Skip building documentation.
         Debian packaging will not know about documentation to exist at all.
         If configured regularly but with the intent not to build the docs,
@@ -32,7 +32,7 @@ Usage:
         Accepted for compatibility, but now ignored.
 
     -h|--help|help
-	Show this help.
+        Show this help.
 EOF
 }
 
@@ -58,10 +58,10 @@ while test $# -ne 0; do
     case "$1" in
     sim|uspace|noauto) echo "I: Argument $1 is accepted for compatibility, but ignored";;
     help|-h|--help) usage; exit 0 ;;
-    no-docs|nodocs|nodoc) unset ENABLE_BUILD_DOCUMENTATION ;;
+    no-docs|nodocs|nodoc|no-doc) unset ENABLE_BUILD_DOCUMENTATION ;;
     *)  echo 1>&2 "Unknown option: $1"
         echo 1>&2
-	usage
+        usage
         exit 99 ;;
     esac
     shift
@@ -88,14 +88,14 @@ if [ -n "$ENABLE_BUILD_DOCUMENTATION" ]; then
     
 
     case $DISTRIB_NAME in
-	Debian-9)
-	    ;; # No xetex in Debian 9 Stretch
-	*)
-	    # Not quite sure which packages is needed for xetex, but
-	    # texlive-xetex seem like a safe choice.  Need xetex to be
-	    # able to build Chinese PDF.
-	    DOC_DEPENDS="$DOC_DEPENDS,\n    texlive-xetex"
-	    ;;
+        Debian-9)
+            ;; # No xetex in Debian 9 Stretch
+        *)
+            # Not quite sure which packages is needed for xetex, but
+            # texlive-xetex seem like a safe choice.  Need xetex to be
+            # able to build Chinese PDF.
+            DOC_DEPENDS="$DOC_DEPENDS,\n    texlive-xetex"
+            ;;
     esac
 else
     DOC_DEPENDS=''
@@ -224,20 +224,27 @@ echo "   The DEB_BUILD_OPTIONS environment variable also works with dpkg-buildpa
 
 if command -v dpkg-checkbuilddeps > /dev/null; then
 
+    a=""
     if [ -n "$ENABLE_BUILD_DOCUMENTATION" ]; then
-        a=$(cd .. && dpkg-checkbuilddeps || true)
+        a=$(cd .. && dpkg-checkbuilddeps 2>&1 || true)
         if [ -n "$a" ]; then
-            echo "W: To successfully build all of LinuxCNC, install the following build dependencies are mising:\n$a"
-            echo "   The missing packages are auto-installed by"
-            echo "     sudo apt build-dep ."
+            echo "W: To successfully build all of LinuxCNC, install the following build dependencies are mising:"
         else
-            echo "I: No build dependencies missing for complete builds including documentation."
+            echo "I: All build dependencies available for complete builds including the documentation."
         fi
     else
-        a=$(cd .. && dpkg-checkbuilddeps -B || true)
+        a=$(cd .. && dpkg-checkbuilddeps -B 2>&1 || true)
         if [ -n "$a" ]; then
-            echo "I: No dependencies missing for building binaries only."
+            echo "W: To successfully build the architecture-dependent parts of LinuxCNC, the following build dependencies are mising:"
+        else
+            echo "I: No dependencies missing while not building the documentation."
         fi
+    fi
+    if [ -n "$a" ]; then
+        # The common part once missing packages have been identified
+        echo -n "    "; echo "$a" | cut -f4 -d:
+        echo "   The missing packages are auto-installed by"
+        echo "     sudo apt build-dep ."
     fi
 else
     echo "W: Tool to check build-dependenices not found"
@@ -248,3 +255,5 @@ else
     echo "   or just execute"
     echo "     sudo apt build-dep ."
 fi
+
+# vim: ts=4
