build: d/configure: severity prefix, instructions

diff --git a/debian/configure b/debian/configure
--- a/debian/configure
+++ b/debian/configure
@@ -22,7 +22,7 @@ Usage:
 
   Extra options:
 
-    no-docs|nodocs
+    no-docs|nodocs|nodoc
         Skip building documentation.
         Debian packaging will not know about documentation to exist at all.
         If configured regularly but with the intent not to build the docs,
@@ -56,9 +56,9 @@ ENABLE_BUILD_DOCUMENTATION=--enable-build-documentation=pdf
 
 while test $# -ne 0; do
     case "$1" in
-    sim|uspace|noauto) echo "$1 is accepted for compatibility, but ignored";;
+    sim|uspace|noauto) echo "I: Argument $1 is accepted for compatibility, but ignored";;
     help|-h|--help) usage; exit 0 ;;
-    no-docs|nodocs) unset ENABLE_BUILD_DOCUMENTATION ;;
+    no-docs|nodocs|nodoc) unset ENABLE_BUILD_DOCUMENTATION ;;
     *)  echo 1>&2 "Unknown option: $1"
         echo 1>&2
 	usage
@@ -123,9 +123,9 @@ case $DISTRIB_NAME in
     Debian-10|Debian-10.*|Raspbian-10|Raspbian-10.*)
         ;;
     *)
-        echo "unknown distribution: $DISTRIB_NAME"
-        echo "detected dependencies may be incomplete or wrong"
-        echo "please consider fixing it and submitting a pull request"
+        echo "W: Unknown distribution: '$DISTRIB_NAME'."
+        echo "   Detected dependencies may be incomplete or wrong."
+        echo "   Please consider fixing it and submitting a pull request."
         ;;
 esac
 
@@ -221,3 +221,30 @@ else
     echo "   Building of documentation is disabled."
 fi
 echo "   The DEB_BUILD_OPTIONS environment variable also works with dpkg-buildpackage."
+
+if command -v dpkg-checkbuilddeps > /dev/null; then
+
+    if [ -n "$ENABLE_BUILD_DOCUMENTATION" ]; then
+        a=$(cd .. && dpkg-checkbuilddeps || true)
+        if [ -n "$a" ]; then
+            echo "W: To successfully build all of LinuxCNC, install the following build dependencies are mising:\n$a"
+            echo "   The missing packages are auto-installed by"
+            echo "     sudo apt build-dep ."
+        else
+            echo "I: No build dependencies missing for complete builds including documentation."
+        fi
+    else
+        a=$(cd .. && dpkg-checkbuilddeps -B || true)
+        if [ -n "$a" ]; then
+            echo "I: No dependencies missing for building binaries only."
+        fi
+    fi
+else
+    echo "W: Tool to check build-dependenices not found"
+    echo "   You may want to install it as follows:"
+    echo "     sudo apt install dpkg-dev"
+    echo "   and directly execute it like this:"
+    echo "     dpkg-checkbuilddeps"
+    echo "   or just execute"
+    echo "     sudo apt build-dep ."
+fi
