cleaned up the runscript, added comments to various sections

diff --git a/scripts/emc.in b/scripts/emc.in
--- a/scripts/emc.in
+++ b/scripts/emc.in
@@ -1,19 +1,39 @@
 #!/bin/bash
-# usage: emc.run [options] [<ini-file>]
+################################################################################
+# usage: emc [options] [<ini-file>]
 #
 # options:
 #     -v = verbose - prints info as it works
 #     -d = echos script commands to screen for debugging
 #
-# if <ini-file> not specified, uses EMC2_DIR/configs/emc.ini
-# if path specified, looks there, else looks in $EMC2_DIR/configs
-
+# A. if <ini-file> not specified, uses $EMC2_CONFIG_DIR/emc.ini
+#
+# B. if <ini-file> is specified a few cases get considered:
+#
+# 1. if /path/to/foo.ini is specified it looks only there
+# 2. if foo.ini is specified, it looks in $EMC2_CONFIG_DIR/foo.ini
+# 3. if only foo is specified, it looks in  $EMC2_CONFIG_DIR/foo/foo.ini,
+# 3.1.           if that fails it then looks at $EMC2_CONFIG_DIR/foo.ini
+#
+################################################################################
+# Author:
+# License: GPL Version 2
+# System: Linux
+#    
+# Copyright (c) 2004 All rights reserved.
+#
+# Last change:
+# $Revision$
+# $Author$
+# $Date$
+################################################################################
 
 DEBUG_FILE=/dev/null
 PRINT_FILE=/dev/null
 
-# strip and process command line options
-#
+################################################################################
+# 1.1. strip and process command line options
+################################################################################
 while ARG=$1 ; ! [ "$ARG" = "${ARG#-}" ] ; do
     # argument is an option
     if [ $ARG = "-d" ] ; then
@@ -33,10 +53,9 @@ while ARG=$1 ; ! [ "$ARG" = "${ARG#-}" ] ; do
     shift
 done
 
-##########################################
-# check for some programs that we need
-# these values  get replaced by configure
-#########################################
+################################################################################
+# 1.2. check for some programs that we need, values get replaced by configure  #
+################################################################################
 INSMOD=@INSMOD@
 RMMOD=@RMMOD@
 LSMOD=@LSMOD@
@@ -48,10 +67,9 @@ AWK=@AWK@
 IPCS=@IPCS@
 KILL=@KILL@
 
-#########################################
-# Directories
-# these values  get replaced by configure
-#########################################
+################################################################################
+# 1.3. Directories                           values get replaced by configure  #
+################################################################################
 prefix=@prefix@
 exec_prefix=@exec_prefix@
 
@@ -71,16 +89,16 @@ docsdir=${prefix}/share/emc/docs
 ncfilesdir=${prefix}/share/emc/ncfiles
 tcldir=${prefix}/share/emc/tcl
 
-#########################################
-# MIsc stuff
-# these values  get replaced by configure
-#########################################
 MODULE_EXT=@MODEXT@ # module extension, used when insmod'ing
 EMC2_HOME=@EMC2_HOME@
+################################################################################
+# 1.3. INIFILE                           find inifile to use                   #
+################################################################################
 
 INIFILE=
 
-#Determine where we ran from
+# 1.3.1. Determine if we have run-in place or installed system
+#        by looking of where the script was run from
 SCRIPT=`which $0 | grep $0`
 echo "SCRIPT=$SCRIPT" >>$PRINT_FILE
 #get the script name
@@ -92,7 +110,7 @@ SCRIPTDIR=$(cd $SCRIPTDIR ; pwd -P)
 echo $SCRIPTDIR >>$PRINT_FILE
 
 if (test "$SCRIPTDIR" = "$EMC2_HOME/scripts");  then
-# for a run-in-place system:
+# 1.3.2. for a run-in-place system:
 EMC2_BIN_DIR=@EMC2_HOME@/bin
 EMC2_TCL_DIR=@EMC2_HOME@/tcl
 EMC2_RTLIB_DIR=@EMC2_HOME@/rtlib
@@ -102,7 +120,7 @@ REALTIME=@EMC2_HOME@/scripts/realtime
 EMC2_IMAGEDIR=@EMC2_HOME@
 
 else
-# for an installed system:
+# 1.3.3. for an installed system:
 EMC2_BIN_DIR=$bindir
 EMC2_TCL_DIR=$tcldir
 EMC2_RTLIB_DIR=$moduledir
@@ -117,7 +135,9 @@ INIVAR=$EMC2_BIN_DIR/inivar
 HALCMD=$EMC2_BIN_DIR/halcmd
 EMC2_EMCSH=$EMC2_BIN_DIR/emcsh
 EMC2_IOSH=$EMC2_BIN_DIR/iosh
-
+#EMC2_CONFIG_DIR may change if the user specifies an ini in a subdir 
+# e.g. configs/stepper, so keep the original value
+EMC2_ORIG_CONFIG_DIR=$EMC2_CONFIG_DIR
 
 # check for root privliges - hope to remove the need for this later
 if [ `$WHOAMI` != root ] ; then
@@ -132,20 +152,33 @@ echo EMC2_TCL_DIR=$EMC2_TCL_DIR >>$PRINT_FILE
 echo EMC2_SCRIPT_DIR=$EMC2_SCRIPT_DIR >>$PRINT_FILE
 echo EMC2_RTLIB_DIR=$EMC2_RTLIB_DIR >>$PRINT_FILE
 echo EMC2_CONFIG_DIR=$EMC2_CONFIG_DIR >>$PRINT_FILE
+echo EMC2_ORIG_CONFIG_DIR=$EMC2_ORIG_CONFIG_DIR >>$PRINT_FILE
 echo INIVAR=$INIVAR >>$PRINT_FILE
 echo HALCMD=$HALCMD >>$PRINT_FILE
 echo EMC2_EMCSH=$EMC2_EMCSH >>$PRINT_FILE
 echo EMC2_IOSH=$EMC2_IOSH >>$PRINT_FILE
 
-# look for ini file
+# 1.3.4. look for ini file, check various places if no abs path specified
 INIFILE=
-if [ ! -n "$1" ] ; then
-# nothing specified, use default
+if [ ! -n "$1" ] ; then                     # nothing specified, use default
     INIFILE=$EMC2_CONFIG_DIR/emc.ini
-elif echo $1 | $GREP / >>$DEBUG_FILE ; then     
-    INIFILE=$1                                 # path specified, use it  
-else                                            
-    INIFILE=$EMC2_CONFIG_DIR/$1                # filename but no path, use default path
+elif echo $1 | $GREP / >>$DEBUG_FILE ; then # something specified, analyse
+    # path specified, use it, but convert it to abs path
+    INI_NAME=`echo $1 | sed s#\^.\*/##`
+    INIF_DIR=`echo $1 | sed s/$INI_NAME//`  # delete name to get path
+    INIF_DIR=$(cd $INIF_DIR ; pwd -P)
+    EMC2_CONFIG_DIR=$INIF_DIR               # remember the found ini dir
+    INIFILE=$INIF_DIR/$INI_NAME
+elif echo $1 | $GREP .ini >>$DEBUG_FILE ; then # filename but no path, check for '.ini'
+    if [-f $EMC2_CONFIG_DIR/$1 ] ; then       # if it exists under configs,
+	INIFILE=$EMC2_CONFIG_DIR/$1         #  use it
+    fi
+else                                        # only name specified, no extension
+    if [-f $EMC2_CONFIG_DIR/$1.ini ] ; then   # check for configs/foo.ini
+	INIFILE=$EMC2_CONFIG_DIR/$1.ini     #  use it
+    elif [-f $EMC2_CONFIG_DIR/$1/$1.ini ] ; then # check for configs/foo/foo.ini
+	INIFILE=$EMC2_CONFIG_DIR/$1/$1.ini  #  use it
+    fi
 fi
 if [ ! -f $INIFILE ] ; then
     echo "Could not find ini file '$INIFILE'"
@@ -153,80 +186,70 @@ if [ ! -f $INIFILE ] ; then
 fi
 echo INIFILE=$INIFILE >>$PRINT_FILE
 
+
 ################################################################################
-# extract info from the ini file that we will need later
-# get name of RS274NGC parameter file
+# 2.  extract info from the ini file that we will need later
 ################################################################################
-RS274NGC_PARAMFILE=`$INIVAR -ini $INIFILE -var PARAMETER_FILE -sec RS274NGC 2>>$DEBUG_FILE`
-if [ ! -n "$RS274NGC_PARAMFILE" ] ; then
-    echo "Can't find variable PARAMETER_FILE in section [RS274NGC] of file $INIFILE."
-    exit -1
-fi
-echo RS274NGC_PARAMFILE=$RS274NGC_PARAMFILE >>$PRINT_FILE
+retval=
 
-# get emcmot information
-EMCMOT=`$INIVAR -ini $INIFILE -var EMCMOT -sec EMCMOT 2>>$DEBUG_FILE`
-if [ ! -n "$EMCMOT" ] ; then
-    echo "Can't find variable EMCMOT in section [EMCMOT] of file $INIFILE."
-    exit -1
-fi
-EMCMOT=$EMCMOT$MODULE_EXT # add module extension
-echo EMCMOT=$EMCMOT >>$PRINT_FILE
+# 2.1. define helper function
+function GetFromIni {
+    #$1 var name   $2 - section name
+    name=$1
+    retval=`$INIVAR -ini $INIFILE -var $1 -sec $2 2>>$DEBUG_FILE`
+    if [ ! -n "$1" ] ; then
+	echo "Can't find variable $1 in section [$2] of file $INIFILE."
+	exit -1
+    fi
+    echo "$name=$retval" >>$PRINT_FILE
+}
+# 2.2. get param file
+GetFromIni PARAMETER_FILE RS274NGC 
+RS274NGC_PARAMFILE=$retval
 
-# get emcio information
-EMCIO=`$INIVAR -ini $INIFILE -var EMCIO -sec EMCIO 2>>$DEBUG_FILE`
-if [ ! -n "$EMCIO" ] ; then
-    echo "Can't find variable EMCIO in section [EMCIO] of file $INIFILE."
-    exit -1
-fi
-echo EMCIO=$EMCIO >>$PRINT_FILE
+# 2.3. get emcmot information
+GetFromIni EMCMOT EMCMOT 
+EMCMOT=$retval$MODULE_EXT # add module extension
 
-# get emctask information
-EMCTASK=`$INIVAR -ini $INIFILE -var TASK -sec TASK 2>>$DEBUG_FILE`
-if [ ! -n "$EMCTASK" ] ; then
-    echo "Can't find variable TASK in section [TASK] of file $INIFILE."
-    exit -1
-fi
-echo EMCTASK=$EMCTASK >>$PRINT_FILE
+# 2.4. get emcio information
+GetFromIni EMCIO EMCIO 
+EMCIO=$retval
 
-# get emcserver information
-EMCSERVER=`$INIVAR -ini $INIFILE -var EMCSERVER -sec EMCSERVER 2>>$DEBUG_FILE`
-# no check needed - if nothing found, nothing will run
-echo EMCSERVER=$EMCSERVER >>$PRINT_FILE
+# 2.5. get emctask information
+GetFromIni TASK TASK 
+EMCTASK=$retval
 
-# get emcstrip information
-EMSTRIP=`$INIVAR -ini $INIFILE -var EMCSTRIP -sec EMCSTRIP 2>>$DEBUG_FILE`
+# 2.6. get emcserver information
+GetFromIni EMCSERVER EMCSERVER 
+EMCSERVER=$retval
+
+# 2.7. get emcstrip information
+GetFromIni EMCSTRIP EMCSTRIP
+EMCSTRIP=$retval
 # if none found, it just won't run... but if found, check for options
 if [ -n "$EMCSTRIP" ] ; then
     EMCSTRIP_OPTIONS=`$INIVAR -ini $INIFILE -var OPTIONS -sec EMCSTRIP 2>>$DEBUG_FILE`
 fi
-echo EMCSTRIP=$EMCSTRIP >>$PRINT_FILE
 echo EMCSTRIP_OPTIONS=$EMCSTRIP_OPTIONS >>$PRINT_FILE
 
-# get display information
-EMCDISPLAY=`$INIVAR -ini $INIFILE -var DISPLAY -sec DISPLAY 2>>$DEBUG_FILE`
-if [ ! -n "$EMCDISPLAY" ] ; then
-    echo "Can't find variable DISPLAY in section [DISPLAY] of file $INIFILE.";
-fi
-echo EMCDISPLAY=$EMCDISPLAY >>$PRINT_FILE
+# 2.8. get display information
+GetFromIni DISPLAY DISPLAY
+EMCDISPLAY=$retval
 
-# get NML config information
-NMLFILE=`$INIVAR -ini $INIFILE -var NML_FILE -sec EMC 2>>$DEBUG_FILE`
-if [ ! -n "$NMLFILE" ] ; then
-    echo "Can't find variable NML_FILE in section [EMC] of file $INIFILE.";
-fi
-echo NMLFILE=$NMLFILE >>$PRINT_FILE
+# 2.9. get NML config information
+GetFromIni NML_FILE EMC
+NMLFILE=$retval
 
 ################################################################################
-# Done gathering information, define a few functions
+# 3. Done gathering information, define a few functions
 # Execution resumes after function definitions...
 ################################################################################
 
 KILL_TASK=
 KILL_TIMEOUT=10
-#
+
 ################################################################################
-# Kills a list of tasks with timeout
+# 3.1. Kills a list of tasks with timeout
 # if it doesn't work, kill -9 is used
 ################################################################################
 function KillTaskWithTimeout() {
@@ -273,12 +296,13 @@ function KillTaskWithTimeout() {
 }
 
 
-# define the cleanup function
+################################################################################
+# 3.2. define the cleanup function
 #
 # this cleanup function doesn't know or care what was actually
 # loaded - it simply kills _any_ processes in it's list of emc
 # components
-
+################################################################################
 function Cleanup() {
 
     echo "Shutting down and cleaning up EMC..."
@@ -349,7 +373,7 @@ function Cleanup() {
 
 
 ################################################################################
-# done with function definitions, execution resumes here
+# 4. done with function definitions, execution resumes here
 ################################################################################
 
 # Name of lock file to check for that signifies that EMC is up,
@@ -378,13 +402,15 @@ trap 'Cleanup ; exit 0' SIGINT SIGTERM
 
 # go to the dir where the config files are
 # either configs/ when run-in-place
-# or /etc/emc2
+# or /usr/local/share/emc/configs (or wherever it was installed to)
 cd $EMC2_CONFIG_DIR
 
 # Create the lock file
 touch $LOCKFILE
 
-# pop up intro graphic
+################################################################################
+# 4.1. pop up intro graphic
+################################################################################
 img=`$INIVAR -ini $INIFILE -var INTRO_GRAPHIC -sec DISPLAY 2>>$DEBUG_FILE`
 imgtime=`$INIVAR -ini $INIFILE -var INTRO_TIME -sec DISPLAY 2>>$DEBUG_FILE`
 if [ "$imgtime" = "" ] ; then
@@ -396,8 +422,9 @@ if [ "$img" != "" ] ; then
   fi
 fi
 
-# Now we can finally start loading EMC
-
+################################################################################
+# 4.2. Now we can finally start loading EMC
+################################################################################
 echo "Loading Real Time OS, RTAPI, and HAL_LIB modules" >>$PRINT_FILE
 if ! $REALTIME start ; then
     echo "Realtime system did not load"
@@ -405,62 +432,48 @@ if ! $REALTIME start ; then
     exit -1
 fi
 
-# Prepare to load real time motion module
+# 4.3. Prepare to load real time motion module
 echo "Loading EMC Motion module: $EMCMOT" >>$PRINT_FILE
 if [ ! -f $EMC2_RTLIB_DIR/$EMCMOT ] ; then
     echo "Can't find motion controller $EMC2_RTLIB_DIR/$EMCMOT"
     Cleanup
     exit -1
 fi
-# get SHMEM_KEY for user/emcmot shared memory area
-SHMEM_KEY=`$INIVAR -ini $INIFILE -var SHMEM_KEY -sec EMCMOT 2>>$DEBUG_FILE`
-if [ ! -n "$SHMEM_KEY" ] ; then
-    echo "Can't find variable SHMEM_KEY in section [EMCMOT] of file $INIFILE."
-    Cleanup
-    exit -1
-fi
-# get thread periods
-BASE_PERIOD_SEC=`$INIVAR -ini $INIFILE -var BASE_PERIOD -sec EMCMOT 2>>$DEBUG_FILE`
-if [ ! -n "$BASE_PERIOD_SEC" ] ; then
-    echo "Can't find variable BASE_PERIOD in section [EMCMOT] of file $INIFILE."
-    Cleanup
-    exit -1
-fi
+# 4.3.1. get SHMEM_KEY for user/emcmot shared memory area
+GetFromIni SHMEM_KEY EMCMOT
+SHMEM_KEY=$retval
+
+# 4.3.2. get thread periods
+GetFromIni BASE_PERIOD EMCMOT
+BASE_PERIOD_SEC=$retval
 BASE_PERIOD_NSEC=`echo $BASE_PERIOD_SEC | env LANG=C $AWK -- '{printf "%d\n", $1*1000000000}'`
-SERVO_PERIOD_SEC=`$INIVAR -ini $INIFILE -var SERVO_PERIOD -sec EMCMOT 2>>$DEBUG_FILE`
-if [ ! -n "$SERVO_PERIOD_SEC" ] ; then
-    echo "Can't find variable SERVO_PERIOD in section [EMCMOT] of file $INIFILE."
-    Cleanup
-    exit -1
-fi
+
+GetFromIni SERVO_PERIOD EMCMOT
+SERVO_PERIOD_SEC=$retval
 SERVO_PERIOD_NSEC=`echo $SERVO_PERIOD_SEC | env LANG=C $AWK -- '{printf "%d\n", $1*1000000000}'`
-TRAJ_PERIOD_SEC=`$INIVAR -ini $INIFILE -var TRAJ_PERIOD -sec EMCMOT 2>>$DEBUG_FILE`
-if [ ! -n "$TRAJ_PERIOD_SEC" ] ; then
-    echo "Can't find variable TRAJ_PERIOD in section [EMCMOT] of file $INIFILE."
-    Cleanup
-    exit -1
-fi
+
+GetFromIni TRAJ_PERIOD EMCMOT
+TRAJ_PERIOD_SEC=$retval
 TRAJ_PERIOD_NSEC=`echo $TRAJ_PERIOD_SEC | env LANG=C $AWK -- '{printf "%d\n", $1*1000000000}'`
 
-# load the motion module
-
+# 4.3.3. load the motion module
 echo "$EMC2_RTLIB_DIR/$EMCMOT base_period=$BASE_PERIOD_NSEC servo_period=$SERVO_PERIOD_NSEC traj_period=$TRAJ_PERIOD_NSEC key=$SHMEM_KEY" >>$PRINT_FILE
 
 if ! $INSMOD $EMC2_RTLIB_DIR/$EMCMOT base_period_nsec=$BASE_PERIOD_NSEC \
-				     servo_period_nsec=$SERVO_PERIOD_NSEC \
-				     traj_period_nsec=$TRAJ_PERIOD_NSEC \
-				     key=$SHMEM_KEY ; then
+		    		    servo_period_nsec=$SERVO_PERIOD_NSEC \
+				    traj_period_nsec=$TRAJ_PERIOD_NSEC \
+				    key=$SHMEM_KEY ; then
     echo "Motion module $EMCMOT did not load..."
     echo "check system log for error messages"
     Cleanup
     exit -1
 fi
 
-# export the location of the HAL realtime modules so that
+# 4.3.4. export the location of the HAL realtime modules so that
 # "halcmd loadrt" can find them
 export HAL_RTMOD_DIR=$EMC2_RTLIB_DIR
 
-# Run emcio in background
+# 4.3.5. Run emcio in background
 echo "Starting EMC IO program: $EMCIO" >>$PRINT_FILE
 if [ ! -x $EMC2_BIN_DIR/$EMCIO ] ; then
     echo "Can't execute IO program $EMC2_BIN_DIR/$EMCIO"
@@ -469,18 +482,25 @@ if [ ! -x $EMC2_BIN_DIR/$EMCIO ] ; then
 fi
 $EMC2_BIN_DIR/$EMCIO -ini $INIFILE &
 
-# execute HALCMD config files (if any)
+# 4.3.6. execute HALCMD config files (if any)
 # get first config file name from ini file
 NUM=1
 CFGFILE=`$INIVAR -ini $INIFILE -var HALFILE -sec HAL -num $NUM 2>>$DEBUG_FILE`
 while [ -n "$CFGFILE" ] ; do
     if [ ! -f $EMC2_CONFIG_DIR/$CFGFILE ] ; then
-	echo "Can't find HAL config file: $EMC2_CONFIG_DIR/$CFGFILE"
-	Cleanup
-	exit -1
+	# try to see maybe we find it in the original dir
+	if [ ! -f $EMC2_ORIG_CONFIG_DIR/$CFGFILE ] ; then
+	    echo "Can't find HAL config file: $EMC2_CONFIG_DIR/$CFGFILE"
+	    Cleanup
+	    exit -1
+	else
+	    CFGFILE=$EMC2_ORIG_CONFIG_DIR/$CFGFILE
+	fi
+    else
+	CFGFILE=$EMC2_CONFIG_DIR/$CFGFILE
     fi
     echo "Running HAL config file $CFGFILE" >>$PRINT_FILE
-    if ! $HALCMD -i $INIFILE -f $EMC2_CONFIG_DIR/$CFGFILE ; then
+    if ! $HALCMD -i $INIFILE -f $CFGFILE ; then
 	echo "HAL config file $CFGFILE failed."
 	Cleanup
 	exit -1
@@ -490,7 +510,7 @@ while [ -n "$CFGFILE" ] ; do
     CFGFILE=`$INIVAR -ini $INIFILE -var HALFILE -sec HAL -num $NUM 2>>$DEBUG_FILE`
 done
 
-# execute discrete HAL commands from ini file (if any)
+# 4.3.7. execute discrete HAL commands from ini file (if any)
 # get first command from ini file
 NUM=1
 HALCOMMAND=`$INIVAR -ini $INIFILE -var HALCMD -sec HAL -num $NUM 2>>$DEBUG_FILE`
@@ -508,10 +528,10 @@ while [ -n "$HALCOMMAND" ] ; do
     HALCOMMAND=`$INIVAR -ini $INIFILE -var HALCMD -sec HAL -num $NUM 2>>$DEBUG_FILE`
 done
 
-# start the realtime stuff ticking
+# 4.3.8. start the realtime stuff ticking
 $HALCMD start
 
-# Run emctask in background
+# 4.3.9. Run emctask in background
 echo "Starting EMC TASK program: $EMCTASK" >>$PRINT_FILE
 if [ ! -x $EMC2_BIN_DIR/$EMCTASK ] ; then
     echo "Can't execute TASK program $EMC2_BIN_DIR/$EMCTASK"
@@ -520,7 +540,7 @@ if [ ! -x $EMC2_BIN_DIR/$EMCTASK ] ; then
 fi
 $EMC2_BIN_DIR/$EMCTASK -ini $INIFILE &
 
-# Run emcserver in background, if necessary
+# 4.3.10. Run emcserver in background, if necessary
 if [ -n "$EMCSERVER" ] ; then
     echo "Starting EMC server program: $EMCSERVER" >>$PRINT_FILE
     if [ ! -x $EMC2_BIN_DIR/$EMCSERVER ] ; then
@@ -531,7 +551,7 @@ if [ -n "$EMCSERVER" ] ; then
     $EMC2_BIN_DIR/$EMCSERVER -ini $INIFILE &
 fi
 
-# Run emcstrip in background, if necessary
+# 4.3.11. Run emcstrip in background, if necessary
 if [ -n "$EMCSTRIP" ] ; then
     echo "Starting EMC stripchart program: $EMCSTRIP" >>$PRINT_FILE
     if [ ! -x $EMC2_BIN_DIR/$EMCSTRIP ] ; then
@@ -549,7 +569,7 @@ $LSMOD >>$DEBUG_FILE
 
 sleep 1
 
-# Run display in foreground
+# 4.3.12. Run display in foreground
 echo "Starting EMC DISPLAY program: $EMCDISPLAY" >>$PRINT_FILE
 case $EMCDISPLAY in
   tkemc|mini)
