qtplasmac migration from plasmac

diff --git a/scripts/linuxcnc.in b/scripts/linuxcnc.in
--- a/scripts/linuxcnc.in
+++ b/scripts/linuxcnc.in
@@ -453,6 +453,19 @@ if [ "$retval" != "1.1" ]; then
     esac
 fi
 
+# 2.1.6 check if PlasmaC config, if true it requires migration to QtPlasmaC
+if [ `$INIVAR -ini "$INIFILE" -var MODE -sec PLASMAC 2> /dev/null` ]; then
+    echo -e "\nThis is a PlasmaC configuration, it requires migrating to QtPlasmac.\n"
+    exitstr=$(qtplasmac-plasmac2qt "$INIFILE")
+    exitval=$?
+    case "$exitval" in
+        0) echo -e "$exitstr";;
+        2) echo -e "Migration cancelled by user.\nPlasmaC is not available in LinuxCNC 2.9 and later.\n";;
+        *) echo -e "QtPlasmaC migration failed with an unknown error.\n";;
+    esac
+    exit 0
+fi
+
 @TCLSH@ $HALLIB_DIR/check_config.tcl "$INIFILE"
 exitval=$?
 case "$exitval" in
