Arrange for the linuxcnc launch script to prompt to auto-convert non JA configs Also includes a number of bug fixes: Ignores missing values rather than putting "None" in the INI Works from anywhere in the tree, not just the config directory Fixes a {} [] confusion.
Signed-off-by: andypugh <andy@bodgesoc.org>

diff --git a/scripts/linuxcnc.in b/scripts/linuxcnc.in
--- a/scripts/linuxcnc.in
+++ b/scripts/linuxcnc.in
@@ -384,6 +384,16 @@ function GetFromIniEx {
     retval="$1"
 }
 
+# 2.1.5 check version
+GetFromIni VERSION EMC
+if [ "$retval" != "1.0" ]; then
+    update_ini -d $INIFILE
+    if [ "$?" != 0 ]; then
+            echo "LinuxCNC startup cancelled by user (or unhandled error)"
+            exit 0
+    fi
+fi
+
 # 2.2. get param file
 GetFromIni PARAMETER_FILE RS274NGC 
 RS274NGC_PARAMFILE=$retval
