linuxcnc launcher: don't try to run update_ini without a DISPLAY
Signed-off-by: Sebastian Kuzminsky <seb@highlab.com>

diff --git a/scripts/linuxcnc.in b/scripts/linuxcnc.in
--- a/scripts/linuxcnc.in
+++ b/scripts/linuxcnc.in
@@ -403,6 +403,10 @@ function GetFromIniEx {
 # 2.1.5 check version
 GetFromIni VERSION EMC
 if [ "$retval" != "1.0" ]; then
+    if [ -z "$DISPLAY" ]; then
+        echo "ini file [EMC]VERSION indicates update is needed, but the update GUI can't run without an X display"
+        exit 1
+    fi
     update_ini -d $INIFILE
     exitval=$?
     case "$exitval" in
