linuxcnc: fix temporary file creation when using include

diff --git a/scripts/linuxcnc.in b/scripts/linuxcnc.in
--- a/scripts/linuxcnc.in
+++ b/scripts/linuxcnc.in
@@ -268,6 +268,12 @@ if [ ! -n "$INIFILE" ] ; then
     exit 0
 fi
 
+# delete directories from path, save name only
+INI_NAME="${INIFILE##*/}"
+INI_DIR="${INIFILE%/*}"
+CONFIG_DIR="${INIFILE%/*}"
+export CONFIG_DIR
+
 function handle_includes () {
   hdr="# handle_includes():"
   inifile=$1 
@@ -278,7 +284,7 @@ function handle_includes () {
     echo "$inifile" ;# just use the input
     return 0 ;# ok
   fi
-  outfile=$(dirname $inifile)/$(basename $inifile).expanded
+  outfile=`mktemp`; # Let the shell create a temporary file
   >|$outfile
   echo "#*** $outfile" >>$outfile
   echo "#*** Created: $(date)" >>$outfile
@@ -315,13 +321,11 @@ function handle_includes () {
   return 0 ;# ok
 }
 
+PREVINIFILE=$INIFILE
 INIFILE=$(handle_includes $INIFILE)
-
-# delete directories from path, save name only
-INI_NAME="${INIFILE##*/}"
-INI_DIR="${INIFILE%/*}"
-CONFIG_DIR="${INIFILE%/*}"
-export CONFIG_DIR
+if [ "$PREVINIFILE" != "$INIFILE" ]; then
+    trap "rm -f $INIFILE" 0 1 2 3 15; # Clean up the temporary file
+fi
 
 export PATH=$CONFIG_DIR/bin:$PATH
 
