scripts-hardening: addressed most of shellcheck

diff --git a/scripts/pyvcp_demo b/scripts/pyvcp_demo
--- a/scripts/pyvcp_demo
+++ b/scripts/pyvcp_demo
@@ -22,7 +22,7 @@
 # You should have received a copy of the GNU General Public License
 # along with this program; if not, write to the Free Software
 # Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
-prog=$(basename $0)
+prog=$(basename "$0")
 
 function usage () {
   cat <<EOF
@@ -52,7 +52,7 @@ EOF
 REALTIME=$(linuxcnc_var REALTIME)
 $REALTIME status >/dev/null
 status=$?
-if [ $status = 0 ] ; then
+if [ "$status" = 0 ] ; then
   msg="$prog: Realtime is already active"
   echo "$msg"
   popup "$msg"
@@ -74,16 +74,16 @@ case $# in
     *) usage;;
 esac
 
-if [ ! -z "$debug" ] ; then
-  echo debug=$debug
-  echo REALTIME=$REALTIME
-  echo XMLFILE=$XMLFILE
-  echo HALFILE=$HALFILE
-  echo COMPNAME=$COMPNAME
+if [ -n "$debug" ] ; then
+  echo "debug=$debug"
+  echo "REALTIME=$REALTIME"
+  echo "XMLFILE=$XMLFILE"
+  echo "HALFILE=$HALFILE"
+  echo "COMPNAME=$COMPNAME"
 fi
 
-cd $(dirname "$XMLFILE") ;# to allow relative includes
-pyvcp -c $COMPNAME $XMLFILE &
+cd "$(dirname "$XMLFILE")" || (echo "E: Could not change directory to '$(dirname "$XMLFILE")'"; exit 1);# to allow relative includes
+pyvcp -c "$COMPNAME" "$XMLFILE" &
 pyvcpjob=$!
 ct=0
 # wait for pins to be created before creating signals
@@ -91,37 +91,38 @@ while true ; do
    halcmd show|grep "${COMPNAME}.*ready" >/dev/null 2>&1
    status=$?
    sleep 1
-   if [ $status == 0 ] ; then
+   if [ "$status" == 0 ] ; then
       #echo "ready after ct=$ct"
       break
    fi
-   if [ $ct -ge 10 ] ; then
+   if [ "$ct" -ge 10 ] ; then
       echo "$0: hal-pyvcp startup failed"
       exit 1
    fi
-   ct=$(($ct+1))
+   ct=$((ct+1))
 done
 
-cd $(dirname "$HALFILE") ;# so HALFILE can source relative files
+cd "$(dirname "$HALFILE")" || (echo "E: Could not change directory to '$(dirname "$HALFILE")'"; exit 1) ;# so HALFILE can source relative files
 
 halmsg=/tmp/pyvcp_demo_halcmd.err
+# Always write to the $halmsg file, first empty the file (the >| overrides 'noclobber')
 >|$halmsg
-halcmd -f $HALFILE >$halmsg 2>&1
+halcmd -f "$HALFILE" > "$halmsg" 2>&1
 halstatus=$?
-if [ $halstatus != 0 ] ; then
+if [ "$halstatus" != 0 ] ; then
   IFS=$'\n' # split lines
   newmsg=
   # put extra blank line between lines of output
   for line in $(cat $halmsg) ; do
-newmsg="$newmsg
+    newmsg="$newmsg
 $line
 "
   done
   popup "$newmsg"
-  kill $pyvcpjob
+  kill "$pyvcpjob"
   halrun -U
   exit 1
 fi
-wait $pyvcpjob
+wait "$pyvcpjob"
 halrun -U
 exit 0
