scripts/realtime:  stop faster and smarter
- Don't sleep 2.5 seconds every time realtime is stopped.
- Fix exit detection for zombies

diff --git a/scripts/realtime.in b/scripts/realtime.in
--- a/scripts/realtime.in
+++ b/scripts/realtime.in
@@ -120,13 +120,28 @@ done
 
 
 
-# wait for a pid to exit
+# wait for a process to exit
 anywait(){
-    pid=$1
-    for (( n=0; $n<20; $((n++)) )); do
+    proc_name=$1
+    tries=${2:-20}
+    sig=${3:-0}
+    pid=$(FindRunningProcs $proc_name)
+    if test -z "$pid"; then
+	return 0 # Already exited
+    fi
+
+    # Kill proc if requested
+    if test -n "$sig"; then
+	kill -$sig "$pid" >/dev/null 2>&1 || return 0
+    fi
+
+    # Wait to see if it exited
+    for (( n=0; $n<$tries; $((n++)) )); do
 	# return success if process died
-	kill -0 "$pid" >/dev/null 2>&1 || return 0
-	# otherwise, wait 1/2 second and try again, up to 10 seconds
+	if ! CheckRunningProcs $proc_name; then
+	    return 0
+	fi
+	# otherwise, wait 1/2 second and try again, up to $tries/2 seconds
 	sleep 0.5
     done
     return 1
@@ -325,19 +340,18 @@ Unload(){
     # This helps to debug issues during the critical shutdown phase;
     # if msgd exited right away those messages would be lost.
 
-    sleep 2.5
-
-    # and get nasty only if it didnt
-    if CheckRunningProcs msgd:$MK_INSTANCE; then
-	MSGD_PID=`FindRunningProcs msgd:$MK_INSTANCE`
-	kill -TERM $MSGD_PID
-	# ...and get even nastier if SIGTERM fails.  FIXME this needs
-	# to be reviewed; if we get this far, then we might need
-	# operator intervention, including debugging
-	if ! anywait $MSGD_PID; then
+    # Wait 2.5s to see if rtapi_msgd exits on its own
+    if ! anywait msgd:$MK_INSTANCE 5 ''; then
+	# It didn't; get nasty
+	echo "ERROR:  msgd:$MK_INSTANCE failed to exit on its own;" \
+	     "sending SIGTERM" >&2
+	if ! anywait msgd:$MK_INSTANCE 20 TERM; then
+	    # ...and get even nastier if SIGTERM fails.  FIXME this needs
+	    # to be reviewed; if we get this far, then we might need
+	    # operator intervention, including debugging
 	    echo "ERROR:  msgd:$MK_INSTANCE failed to exit after SIGTERM;" >&2
 	    echo "sending SIGKILL" >&2
-	    kill -KILL $MSGD_PID
+	    kill -KILL $(FindRunningProcs msgd:$MK_INSTANCE)
 	fi
     fi
 
