during ./configure, if no GTK is found print a message warning that things like halscope won't build

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -3246,13 +3246,17 @@ if test "${with_gtk_ver+set}" = set; then
   withval="$with_gtk_ver"
 
 	case "$withval" in
-	"" | y | ye | yes | n | no)
+	"" | y | ye | yes)
 	    { { echo "$as_me:$LINENO: error: You must supply an argument to --with-gtk_ver." >&5
 echo "$as_me: error: You must supply an argument to --with-gtk_ver." >&2;}
    { (exit 1); exit 1; }; }
 	  ;;
+	n | no | none)
+	    GTK_VER="none"
+	  ;;
+	*)
+	    GTK_VER="$withval"
 	esac
-	GTK_VER="$withval"
 
 fi;
 
@@ -3275,6 +3279,10 @@ if test "x" = "x$GTK_VER"; then
 fi
 echo "$as_me:$LINENO: result: $GTK_VER" >&5
 echo "${ECHO_T}$GTK_VER" >&6
+if (test "none" = "$GTK_VER" ) ; then
+  { echo "$as_me:$LINENO: WARNING: GTK not found, some utilities (halmeter, halscope) will not be built" >&5
+echo "$as_me: WARNING: GTK not found, some utilities (halmeter, halscope) will not be built" >&2;}
+fi
 if (test "1.2" = "$GTK_VER") ; then
   GTK_CFLAGS=`gtk-config --cflags`
   GTK_LIBS=`gtk-config --libs`
