checking for sudo, also allows overrides like this: --with-sudo=/usr/bin/gksudo

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -310,7 +310,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS PACKAGE RTNAME RTAI RTLINUX RTLINUXPRO RTPREFIX KERNELDIR RTFLAGS RTDIR EMC2_HOME AUTODIRS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT WFLAGS CPP EGREP KERNEL_VERS MODEXT BUILD_SYS EXT_RTFLAGS MODULE_DIR GTK_VER GTK_LIBS GTK_CFLAGS CXX CXXFLAGS ac_ct_CXX SET_MAKE RANLIB ac_ct_RANLIB AR GREP INSTALL SED PS KILL WHOAMI AWK INSMOD RMMOD LSMOD PIDOF IPCS USE_LIBM USE_STUBS USE_RTLIBM MATHINC MATHLIB RTAI3_MOD RTAI_MOD RTL_MOD TCL_DBGX TK_DBGX TCL_CFLAGS TK_CFLAGS TCL_LIBS TK_LIBS DATE MAKEFLAGS USE_NLS HAVE_LOCALE_H LANGUAGES HAVE_LIBINTL_H HAVE_LIBINTL LOCALEDIR LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS PACKAGE RTNAME RTAI RTLINUX RTLINUXPRO RTPREFIX KERNELDIR RTFLAGS RTDIR EMC2_HOME AUTODIRS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT WFLAGS CPP EGREP KERNEL_VERS MODEXT BUILD_SYS EXT_RTFLAGS MODULE_DIR GTK_VER GTK_LIBS GTK_CFLAGS CXX CXXFLAGS ac_ct_CXX SET_MAKE RANLIB ac_ct_RANLIB AR GREP INSTALL SED SUDO PS KILL WHOAMI AWK INSMOD RMMOD LSMOD PIDOF IPCS USE_LIBM USE_STUBS USE_RTLIBM MATHINC MATHLIB RTAI3_MOD RTAI_MOD RTL_MOD TCL_DBGX TK_DBGX TCL_CFLAGS TK_CFLAGS TCL_LIBS TK_LIBS DATE MAKEFLAGS USE_NLS HAVE_LOCALE_H LANGUAGES HAVE_LIBINTL_H HAVE_LIBINTL LOCALEDIR LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -860,6 +860,7 @@ Optional Packages:
   --with-kbuild=<y/n>                     Specify if your kernel uses kbuild or not
   --with-module-dir=<module-dir>          Installation directory for kernel modules
   --with-gtk_ver=<GTK-version>            GTK version
+  --with-sudo=<sudo/gksudo>            sudo variant
   --with-make-quiet                       make will run quietly
   --with-locale-dir=DIR   Location of the locale file(s)
                           DATADIR/locale
@@ -3304,6 +3305,28 @@ fi
 # Check for all the utility programs we need to build and install emc        #
 # as well as those we use in the emc scripts...                              #
 ##############################################################################
+
+
+# Check whether --with-sudo or --without-sudo was given.
+if test "${with_sudo+set}" = set; then
+  withval="$with_sudo"
+
+	case "$withval" in
+	"" | y | ye | yes)
+	    { { echo "$as_me:$LINENO: error: You must supply an argument to --with-sudo." >&5
+echo "$as_me: error: You must supply an argument to --with-sudo." >&2;}
+   { (exit 1); exit 1; }; }
+	  ;;
+	n | no | none)
+	    SUDO=""
+	  ;;
+	*)
+	    SUDO="$withval"
+	esac
+
+fi;
+
+
 ac_ext=cc
 ac_cpp='$CXXCPP $CPPFLAGS'
 ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
@@ -3928,6 +3951,47 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
+# Extract the first word of "sudo", so it can be a program name with args.
+set dummy sudo; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_SUDO+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $SUDO in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_SUDO="$SUDO" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+as_dummy="/bin:/usr/bin:/usr/local/bin"
+for as_dir in $as_dummy
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_SUDO="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  test -z "$ac_cv_path_SUDO" && ac_cv_path_SUDO=""""
+  ;;
+esac
+fi
+SUDO=$ac_cv_path_SUDO
+
+if test -n "$SUDO"; then
+  echo "$as_me:$LINENO: result: $SUDO" >&5
+echo "${ECHO_T}$SUDO" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
 # Extract the first word of "ps", so it can be a program name with args.
 set dummy ps; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
@@ -4296,6 +4360,7 @@ else
   echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
+
 
 
 
@@ -6771,6 +6836,7 @@ s,@AR@,$AR,;t t
 s,@GREP@,$GREP,;t t
 s,@INSTALL@,$INSTALL,;t t
 s,@SED@,$SED,;t t
+s,@SUDO@,$SUDO,;t t
 s,@PS@,$PS,;t t
 s,@KILL@,$KILL,;t t
 s,@WHOAMI@,$WHOAMI,;t t
