regenerate

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -5773,12 +5773,12 @@ fi
 
 echo "$as_me:$LINENO: checking for BWidget" >&5
 echo $ECHO_N "checking for BWidget... $ECHO_C" >&6
-if  (unset DISPLAY; echo "catch { package require bwidget }; exit [expr [lsearch [package names] BWixdget] == -1]" | tclsh) ; then
+if  (unset DISPLAY; echo "catch { package require bwidget }; exit [expr [lsearch [package names] BWidget] == -1]" | tclsh) ; then
     echo "$as_me:$LINENO: result: found" >&5
 echo "${ECHO_T}found" >&6
 else
-    { { echo "$as_me:$LINENO: error: bwidget not found" >&5
-echo "$as_me: error: bwidget not found" >&2;}
+    { { echo "$as_me:$LINENO: error: not found" >&5
+echo "$as_me: error: not found" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
