bjt wants to continue editing docs on ubuntu 6.06 for now, so make that OK
the infrastructural changes will remain, so we can revisit this decision later
after we drop dapper support in the stable version

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -5547,14 +5547,14 @@ echo $ECHO_N "checking for LyX version... $ECHO_C" >&6; }
     { echo "$as_me:$LINENO: result: $LYX_VER" >&5
 echo "${ECHO_T}$LYX_VER" >&6; }
     set -- `echo $LYX_VER | sed 's/\./ /g'`
-    if test $1 -lt 1 -o \( $1 -eq 1 -a $2 -lt 5 \) -o \( $1 -eq 1 -a $2 -eq 5 -a $3 -lt 3 \); then
-	{ { echo "$as_me:$LINENO: error: LyX version less than 1.5.3, documentation cannot be built" >&5
-echo "$as_me: error: LyX version less than 1.5.3, documentation cannot be built" >&2;}
+    if test $1 -lt 1 -o \( $1 -eq 1 -a $2 -lt 3 \) -o \( $1 -eq 1 -a $2 -eq 3 -a $3 -lt 6 \); then
+	{ { echo "$as_me:$LINENO: error: LyX version less than 1.3.6, documentation cannot be built" >&5
+echo "$as_me: error: LyX version less than 1.3.6, documentation cannot be built" >&2;}
    { (exit 1); exit 1; }; }
     fi
-    if test $1 -gt 1 -o \( $1 -eq 1 -a $2 -gt 5 \); then
-	    { echo "$as_me:$LINENO: WARNING: LyX documentation should only be edited with LyX version 1.5.x" >&5
-echo "$as_me: WARNING: LyX documentation should only be edited with LyX version 1.5.x" >&2;}
+    if test $1 -gt 1 -o \( $1 -eq 1 -a $2 -gt 3 \); then
+	    { echo "$as_me:$LINENO: WARNING: LyX documentation should only be edited with LyX version 1.3.x" >&5
+echo "$as_me: WARNING: LyX documentation should only be edited with LyX version 1.3.x" >&2;}
     fi
     # Extract the first word of "convert", so it can be a program name with args.
 set dummy convert; ac_word=$2
