merge the new_cl_branch: a port of classicladder 0.7.100 to emc2's hal

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -872,7 +872,6 @@ Optional Packages:
   --with-kernel-headers=<directory>       Location for kernel headers
   --with-kbuild=<y/n>                     Specify if your kernel uses kbuild or not
   --with-module-dir=<module-dir>          Installation directory for kernel modules
-  --with-gtk_ver=<GTK-version>            GTK version
   --with-rmmod=</path/rmmod>              rmmod variant
   --with-insmod=</path/insmod>            insmod variant
   --with-python=<path>                    Specify the Python interpreter
@@ -3583,64 +3582,38 @@ _ACEOF
 
 # Check for GTK
 # accept GTK_VER from command line
-echo "$as_me:$LINENO: checking for GTK version" >&5
-echo $ECHO_N "checking for GTK version... $ECHO_C" >&6
+echo "$as_me:$LINENO: checking for GTK" >&5
+echo $ECHO_N "checking for GTK... $ECHO_C" >&6
 
-
-# Check whether --with-gtk_ver or --without-gtk_ver was given.
-if test "${with_gtk_ver+set}" = set; then
-  withval="$with_gtk_ver"
-
-	case "$withval" in
-	"" | y | ye | yes)
-	    { { echo "$as_me:$LINENO: error: You must supply an argument to --with-gtk_ver." >&5
-echo "$as_me: error: You must supply an argument to --with-gtk_ver." >&2;}
-   { (exit 1); exit 1; }; }
-	  ;;
-	n | no | none)
-	    GTK_VER="none"
-	  ;;
-	*)
-	    GTK_VER="$withval"
-	esac
-
-fi;
-
-if test "x" = "x$GTK_VER"; then
-  #we need to find out GTK_VER ourselves
-  GTK_VER="none"
-  if type gtk-config 2>/dev/null >/dev/null ; then
-    # found gtk-config, that means GTK 1.2 is installed
-    GTK_VER="1.2"
-  fi
-  if type pkg-config 2>/dev/null >/dev/null ; then
-    # found pkg-config, that means GTK 2.x _might_ be installed
-    if pkg-config gtk+-2.0 --exists ; then
-      # found the .pc file for gtk-2.0
-      GTK_VER="2.0"
-    elif pkg-config gtk+-2.2 --exists ; then
-      # found the .pc file for gtk-2.2
-      GTK_VER="2.2"
-    fi
-  fi
+if type pkg-config 2>/dev/null >/dev/null ; then
+# found pkg-config, that means GTK 2.x _might_ be installed
+if pkg-config gtk+-2.0 --exists ; then
+  # found the .pc file for gtk-2.0
+  GTK_VER="2.0"
+elif pkg-config gtk+-2.2 --exists ; then
+  # found the .pc file for gtk-2.2
+  GTK_VER="2.2"
 fi
+
 echo "$as_me:$LINENO: result: $GTK_VER" >&5
 echo "${ECHO_T}$GTK_VER" >&6
 if (test "none" = "$GTK_VER" ) ; then
-  { echo "$as_me:$LINENO: WARNING: GTK not found, some utilities (halmeter, halscope) will not be built" >&5
-echo "$as_me: WARNING: GTK not found, some utilities (halmeter, halscope) will not be built" >&2;}
-fi
-if (test "1.2" = "$GTK_VER") ; then
-  GTK_CFLAGS=`gtk-config --cflags`
-  GTK_LIBS=`gtk-config --libs`
-elif ( (test "2.0" = "$GTK_VER") || (test "2.2" = "$GTK_VER") ) ; then
+  { echo "$as_me:$LINENO: WARNING: GTK2 not found, some utilities (halmeter, halscope) will not be built" >&5
+echo "$as_me: WARNING: GTK2 not found, some utilities (halmeter, halscope) will not be built" >&2;}
+else
   GTK_CFLAGS=`pkg-config gtk+-$GTK_VER --cflags`
   GTK_LIBS=`pkg-config gtk+-$GTK_VER --libs`
-else
-  GTK_CFLAGS=""
-  GTK_LIBS=""
-  GTK_VER=""
+  if pkg-config --exists libgnomeprintui-2.2; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_GNOMEPRINT
+_ACEOF
+
+    GTK_CFLAGS="$GTK_CFLAGS `pkg-config --cflags libgnomeprintui-2.2`
+    GTK_LIBS="$GTK_LIBS `pkg-config --libs libgnomeprintui-2.2`
+  fi
 fi
+
 
 
 
